#!/usr/bin/env python3
"""signals.vss -> the tables every side uses:
  firmware/t1s_node/vss_dict.h    (C, the ESP)
  sdv/python/t1s_sdv/vss_dict.py  (Python: host library, console)
  sdv/js/vss_dict.js              (browser / Node)
    python3 sdv/gen.py [--also <dir>]...     extra copies of the Python package (e.g. a console that vendors it)
The dictionary hash (CRC-16 over "id path type" lines) is in all three, and the ESP reports it in HELLO, so a host
with another dictionary is told so instead of decoding the wrong values."""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TYPES = {"bool": (0, 1), "u8": (1, 1), "i8": (2, 1), "u16": (3, 2), "i16": (4, 2), "u32": (5, 4), "i32": (6, 4), "f32": (7, 4)}


def crc16(b, c=0xFFFF):
    for x in b:
        c ^= x << 8
        for _ in range(8):
            c = ((c << 1) ^ 0x1021) & 0xFFFF if c & 0x8000 else (c << 1) & 0xFFFF
    return c


def load():
    sigs = []
    for ln in open(os.path.join(HERE, "signals.vss")):
        ln = ln.rstrip("\n")
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        f = ln.split(None, 5)
        sid, path, typ, unit, acc = int(f[0], 16), f[1], f[2], f[3], f[4]
        note = f[5].strip() if len(f) > 5 else ""
        assert 0 < sid <= 0x3FFF and typ in TYPES and acc in ("s", "a"), ln
        assert re.fullmatch(r"Vehicle(\.[A-Za-z0-9_]+)+", path), path
        sigs.append((sid, path, typ, "" if unit == "-" else unit, acc, note))
    assert len({s[0] for s in sigs}) == len(sigs) and len({s[1] for s in sigs}) == len(sigs), "duplicate id or path"
    return sorted(sigs)


def main():
    sigs = load()
    h = crc16("\n".join("%04x %s %s" % (s[0], s[1], s[2]) for s in sigs).encode())
    head = "generated by sdv/gen.py from sdv/signals.vss -- do not edit"
    # C
    c = ["// " + head, "#pragma once", "#include <stdint.h>", "",
         "#define VSS_DICT_HASH 0x%04x" % h, "#define VSS_N %d" % len(sigs),
         "enum { VT_BOOL, VT_U8, VT_I8, VT_U16, VT_I16, VT_U32, VT_I32, VT_F32 };",
         "typedef struct { uint16_t id; uint8_t type, size, actuator; const char *path, *unit; } vss_sig_t;", ""]
    for s in sigs:
        c.append("#define VSS_%s 0x%04x" % (re.sub(r"[^A-Za-z0-9]", "_", s[1][8:]).upper(), s[0]))
    c += ["", "static const vss_sig_t VSS_SIGS[VSS_N] = {"]
    for s in sigs:
        t, n = TYPES[s[2]]
        c.append('  {0x%04x, %d, %d, %d, "%s", "%s"},' % (s[0], t, n, s[4] == "a", s[1], s[3]))
    c += ["};", ""]
    open(os.path.join(ROOT, "firmware", "t1s_node", "vss_dict.h"), "w").write("\n".join(c))
    # Python
    p = ['"""%s"""' % head, "HASH = 0x%04x" % h,
         "# (id, path, type, unit, access s|a, note)", "SIGNALS = ["]
    p += ["    (0x%04x, %r, %r, %r, %r, %r)," % s for s in sigs] + ["]", ""]
    out = os.path.join(HERE, "python", "t1s_sdv", "vss_dict.py")
    open(out, "w").write("\n".join(p))
    # JS
    j = ["// " + head, "export const HASH = 0x%04x;" % h, "export const SIGNALS = ["]
    j += ['  [0x%04x, "%s", "%s", "%s", "%s"],' % s[:5] for s in sigs] + ["];", ""]
    open(os.path.join(HERE, "js", "vss_dict.js"), "w").write("\n".join(j))
    a = sys.argv[1:]
    for i, k in enumerate(a):
        if k == "--also":
            dst = os.path.join(a[i + 1], "t1s_sdv")
            shutil.rmtree(dst, ignore_errors=True)
            shutil.copytree(os.path.join(HERE, "python", "t1s_sdv"), dst, ignore=shutil.ignore_patterns("__pycache__"))
            print("copied to", dst)
    print("%d signals, hash 0x%04x" % (len(sigs), h))


if __name__ == "__main__":
    main()
