// generated by sdv/gen.py from sdv/signals.vss -- do not edit
#pragma once
#include <stdint.h>

#define VSS_DICT_HASH 0x27e3
#define VSS_N 30
enum { VT_BOOL, VT_U8, VT_I8, VT_U16, VT_I16, VT_U32, VT_I32, VT_F32 };
typedef struct { uint16_t id; uint8_t type, size, actuator; const char *path, *unit; } vss_sig_t;

#define VSS_SPEED 0x0101
#define VSS_POWERTRAIN_TRANSMISSION_SELECTEDGEAR 0x0102
#define VSS_CHASSIS_STEERINGWHEEL_ANGLE 0x0103
#define VSS_CHASSIS_ACCELERATOR_PEDALPOSITION 0x0104
#define VSS_CHASSIS_BRAKE_PEDALPOSITION 0x0105
#define VSS_PRIVATE_DRIVINGMODE 0x0106
#define VSS_BODY_LIGHTS_DIRECTIONINDICATOR_LEFT_ISSIGNALING 0x0201
#define VSS_BODY_LIGHTS_DIRECTIONINDICATOR_RIGHT_ISSIGNALING 0x0202
#define VSS_BODY_LIGHTS_HAZARD_ISSIGNALING 0x0203
#define VSS_BODY_LIGHTS_BRAKE_ISACTIVE 0x0204
#define VSS_BODY_LIGHTS_BACKUP_ISON 0x0205
#define VSS_BODY_LIGHTS_BEAM_HIGH_ISON 0x0206
#define VSS_PRIVATE_LIGHTS_DIRECTIONINDICATOR_LEFT_ISLIT 0x0207
#define VSS_PRIVATE_LIGHTS_DIRECTIONINDICATOR_RIGHT_ISLIT 0x0208
#define VSS_BODY_HORN_ISACTIVE 0x0301
#define VSS_CABIN_DOOR_ROW1_DRIVERSIDE_ISOPEN 0x0302
#define VSS_CABIN_DOOR_ROW1_PASSENGERSIDE_ISOPEN 0x0303
#define VSS_CABIN_DOOR_ROW2_DRIVERSIDE_ISOPEN 0x0304
#define VSS_CABIN_DOOR_ROW2_PASSENGERSIDE_ISOPEN 0x0305
#define VSS_PRIVATE_EXTERNAL_PROXIMITY_REAR 0x0401
#define VSS_PRIVATE_ZONE_PROXIMITY_RAW 0x0402
#define VSS_PRIVATE_ZONE_STICK_X 0x0403
#define VSS_PRIVATE_ZONE_STICK_Y 0x0404
#define VSS_PRIVATE_ZONE_STICK_GEARFLICK 0x0405
#define VSS_PRIVATE_ZONE_LOOPWORKTIME 0x0406
#define VSS_PRIVATE_ZONE_RCPFAILURES 0x0407
#define VSS_PRIVATE_ZONE_BRIGHTNESS 0x0408
#define VSS_PRIVATE_TEST_PING 0x0501
#define VSS_PRIVATE_TEST_PONG 0x0502
#define VSS_PRIVATE_TEST_COUNTER 0x0503

static const vss_sig_t VSS_SIGS[VSS_N] = {
  {0x0101, 7, 4, 0, "Vehicle.Speed", "km/h"},
  {0x0102, 2, 1, 1, "Vehicle.Powertrain.Transmission.SelectedGear", ""},
  {0x0103, 4, 2, 0, "Vehicle.Chassis.SteeringWheel.Angle", "degrees"},
  {0x0104, 1, 1, 0, "Vehicle.Chassis.Accelerator.PedalPosition", "percent"},
  {0x0105, 1, 1, 0, "Vehicle.Chassis.Brake.PedalPosition", "percent"},
  {0x0106, 1, 1, 0, "Vehicle.Private.DrivingMode", ""},
  {0x0201, 0, 1, 0, "Vehicle.Body.Lights.DirectionIndicator.Left.IsSignaling", ""},
  {0x0202, 0, 1, 0, "Vehicle.Body.Lights.DirectionIndicator.Right.IsSignaling", ""},
  {0x0203, 0, 1, 0, "Vehicle.Body.Lights.Hazard.IsSignaling", ""},
  {0x0204, 0, 1, 0, "Vehicle.Body.Lights.Brake.IsActive", ""},
  {0x0205, 0, 1, 0, "Vehicle.Body.Lights.Backup.IsOn", ""},
  {0x0206, 0, 1, 0, "Vehicle.Body.Lights.Beam.High.IsOn", ""},
  {0x0207, 0, 1, 0, "Vehicle.Private.Lights.DirectionIndicator.Left.IsLit", ""},
  {0x0208, 0, 1, 0, "Vehicle.Private.Lights.DirectionIndicator.Right.IsLit", ""},
  {0x0301, 0, 1, 0, "Vehicle.Body.Horn.IsActive", ""},
  {0x0302, 0, 1, 0, "Vehicle.Cabin.Door.Row1.DriverSide.IsOpen", ""},
  {0x0303, 0, 1, 0, "Vehicle.Cabin.Door.Row1.PassengerSide.IsOpen", ""},
  {0x0304, 0, 1, 0, "Vehicle.Cabin.Door.Row2.DriverSide.IsOpen", ""},
  {0x0305, 0, 1, 0, "Vehicle.Cabin.Door.Row2.PassengerSide.IsOpen", ""},
  {0x0401, 7, 4, 0, "Vehicle.Private.External.proximity_rear", "m"},
  {0x0402, 3, 2, 0, "Vehicle.Private.Zone.Proximity.Raw", ""},
  {0x0403, 3, 2, 0, "Vehicle.Private.Zone.Stick.X", ""},
  {0x0404, 3, 2, 0, "Vehicle.Private.Zone.Stick.Y", ""},
  {0x0405, 1, 1, 0, "Vehicle.Private.Zone.Stick.GearFlick", ""},
  {0x0406, 3, 2, 0, "Vehicle.Private.Zone.LoopWorkTime", "us"},
  {0x0407, 3, 2, 0, "Vehicle.Private.Zone.RcpFailures", ""},
  {0x0408, 1, 1, 1, "Vehicle.Private.Zone.Brightness", "percent"},
  {0x0501, 5, 4, 0, "Vehicle.Private.Test.Ping", ""},
  {0x0502, 5, 4, 0, "Vehicle.Private.Test.Pong", ""},
  {0x0503, 5, 4, 0, "Vehicle.Private.Test.Counter", ""},
};
